import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer, alice, bob, carol] = await ethers.getSigners();

  // 60s for local demo; 24h for testnet
  const refundDelay =
    network.name === "localhost" || network.name === "hardhat" ? 60 : 86400;

  console.log("Deploying with:", deployer.address);
  console.log("Network:", network.name, "| refundDelay:", refundDelay, "seconds");

  const MockQIEUSD = await ethers.getContractFactory("MockQIEUSD");
  const mockToken = await MockQIEUSD.deploy();
  await mockToken.waitForDeployment();
  const mockAddress = await mockToken.getAddress();
  console.log("MockQIEUSD:", mockAddress);

  const ReputationPay = await ethers.getContractFactory("ReputationPay");
  const reputationPay = await ReputationPay.deploy(refundDelay);
  await reputationPay.waitForDeployment();
  const repAddress = await reputationPay.getAddress();
  console.log("ReputationPay:", repAddress);

  const mintAmount = ethers.parseUnits("10000", 18);
  const demoAddresses = [deployer.address, alice.address, bob.address, carol.address];

  for (const addr of demoAddresses) {
    await (await mockToken.mint(addr, mintAmount)).wait();
    console.log("Minted 10000 QIEUSD to", addr);
  }

  const amount1 = ethers.parseUnits("250", 18);
  await (
    await reputationPay
      .connect(alice)
      .createPaymentRequest(
        bob.address,
        mockAddress,
        amount1,
        "Brand Identity Design",
        "Logo and brand guidelines for AI research lab"
      )
  ).wait();

  const amount2 = ethers.parseUnits("500", 18);
  await (
    await reputationPay
      .connect(bob)
      .createPaymentRequest(
        carol.address,
        mockAddress,
        amount2,
        "Research Dataset License",
        "Curated dataset for merchant analytics"
      )
  ).wait();

  const chainId = (await ethers.provider.getNetwork()).chainId;
  const explorerBase =
    chainId === 1983n
      ? "https://testnet.qie.digital"
      : chainId === 31337n
        ? ""
        : "";

  const envContent = `# Auto-generated by deploy script
NEXT_PUBLIC_MOCK_QIEUSD_ADDRESS=${mockAddress}
NEXT_PUBLIC_REPUTATION_PAY_ADDRESS=${repAddress}
NEXT_PUBLIC_CHAIN_ID=${chainId}
`;

  const envPath = path.join(__dirname, "../frontend/.env.local");
  fs.writeFileSync(envPath, envContent);
  console.log("Wrote", envPath);

  const contractsPath = path.join(__dirname, "../frontend/lib/deployed.ts");
  const contractsContent = `// Auto-generated - do not edit manually
export const DEPLOYED = {
  chainId: ${chainId},
  mockQIEUSD: "${mockAddress}" as const,
  reputationPay: "${repAddress}" as const,
  refundDelay: ${refundDelay},
} as const;
`;
  fs.writeFileSync(contractsPath, contractsContent);

  const deployInfoPath = path.join(__dirname, "../docs/deployed-addresses.md");
  const deployInfo = `# Deployed Contract Addresses

> Auto-generated on ${new Date().toISOString().split("T")[0]} — network: **${network.name}** (chainId: ${chainId})

| Contract | Address |
|----------|---------|
| MockQIEUSD | \`${mockAddress}\` |
| ReputationPay | \`${repAddress}\` |

## Explorer Links (QIE Testnet)

${explorerBase ? `- [MockQIEUSD](${explorerBase}/address/${mockAddress})` : "- Run on QIE testnet for explorer links"}
${explorerBase ? `- [ReputationPay](${explorerBase}/address/${repAddress})` : ""}

## Refund delay

${refundDelay} seconds (${refundDelay === 60 ? "demo/local" : "24h testnet"})
`;
  fs.mkdirSync(path.dirname(deployInfoPath), { recursive: true });
  fs.writeFileSync(deployInfoPath, deployInfo);
  console.log("Wrote", deployInfoPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
